name: f1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.68.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.0.0
  shared_preferences: ^2.3.0
  percent_indicator: ^4.2.3
  lottie: ^2.7.0
  firebase_core: ^2.22.0
  intl: ^0.19.0
  firebase_auth: ^4.10.0
  firebase_auth_web: ^5.11.0
  image_picker: ^1.1.1
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
      - asset/animations/fire.json
      - asset/_DSC0032.jpg




